#!/usr/bin/env python3
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Generate lightweight API docs for public QuMat Python interfaces."""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from qumat.qdp import QdpEngine, QuantumTensor
from qumat.qumat import QuMat


OUT_PATH = ROOT / "docs" / "qumat" / "api-autogen.md"


def _first_line(obj: object) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.splitlines()[0].strip() if doc else "No documentation provided."


def _safe_signature(obj: object) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "()"


def _public_methods(cls: type) -> list[tuple[str, object]]:
    methods: list[tuple[str, object]] = []
    for name, member in inspect.getmembers(cls, predicate=inspect.isfunction):
        if name.startswith("_") and name != "__init__":
            continue
        methods.append((name, member))
    return methods


def _render_class(cls: type) -> list[str]:
    lines = [f"## `{cls.__module__}.{cls.__name__}`", ""]
    lines.append(_first_line(cls))
    if cls.__module__ == "qumat.qdp":
        lines.append("")
        lines.append(
            "Note: QDP native symbols come from the `_qdp` extension at runtime. "
            "See `docs/qdp/api.md` for full behavior and constraints."
        )
    lines.append("")
    lines.append("### Methods")
    lines.append("")

    for method_name, method in _public_methods(cls):
        lines.append(f"- `{method_name}{_safe_signature(method)}`")
        lines.append(f"  - {_first_line(method)}")
    lines.append("")
    return lines


def build_doc() -> str:
    lines = [
        "---",
        "title: Auto-generated Python API",
        "sidebar_label: Python API (Auto)",
        "---",
        "",
        "# Auto-generated Python API",
        "",
        "This page is generated from source by `scripts/generate_qumat_api_docs.py`.",
        "Do not edit this file manually.",
        "",
    ]
    for cls in (QuMat, QdpEngine, QuantumTensor):
        lines.extend(_render_class(cls))

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUT_PATH.write_text(build_doc(), encoding="utf-8")
    print(f"Generated {OUT_PATH}")


if __name__ == "__main__":
    main()
